// <auto-generated />
namespace SchoolERPSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RandomNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RandomNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201911211634546_Random-Number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
